# Created with YamlCreate.ps1 v2.4.1 $debug=NVS1.CRLF.7-4-2.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.12.0.schema.json

PackageIdentifier: VoiceMeet.VoiceMeet.Beta
PackageVersion: 0.0.7.8
PackageLocale: ko-KR
Publisher: VoiceMeet
PublisherUrl: https://voicemeet.net
PublisherSupportUrl: https://voicemeet.net/support
PrivacyUrl: https://voicemeet.net/legal/privacy
Author: kjxbyz
PackageName: VoiceMeet Beta
PackageUrl: https://voicemeet.net
License: GPL-3.0-only
LicenseUrl: https://voicemeet.net/license
Copyright: Copyright (c) 2025 VoiceMeet
ShortDescription: 목소리를 통해 세상을 만나보세요.
Description: |
  VoiceMeet는 음성을 기반으로 한 새로운 소셜 앱으로, 화면의 장벽을 허물고 음성을 통해 진정한 관계를 만들어갈 수 있도록 도와줍니다.

  주요 기능:
  
  - 음성 매칭 – 마음이 맞는 목소리를 찾아보세요: 실시간 음성 매칭으로 목소리만으로 새로운 친구를 만날 수 있습니다.
  - 음성 채팅방 – 언제 어디서든 자유롭게 채팅하세요: 테마별 음성 채팅방에 참여하여 게임, 음악, 연애 등 좋아하는 주제에 대해 이야기해 보세요.
  - 음성 카드 – 목소리로 이야기를 들려주세요: 짧은 음성 소개로 당신의 개성과 따뜻함을 보여주세요.
  - 귓속말 – 1:1 음성 채팅: 안전하고 편안한 느낌의 저지연 고품질 1인 통화를 즐겨보세요.
  - 음성 필터 – 나만의 목소리 만들기: 다양한 음성 효과와 필터를 사용하여 목소리 톤과 스타일을 더욱 돋보이게 만들어 보세요.
  - 음성 피드 – 다양한 소리의 세계를 탐험하세요: 음성 게시물을 스크롤하며 다른 사람들과 소통하고, 공감하는 주제를 찾아보세요.
  
  새로운 친구를 사귀거나, 관심 있는 주제를 탐색하거나, 공감하는 목소리를 발견하든, VoiceMeet는 음성 상호작용을 위한 무료의 따뜻하고 매력적인 공간을 제공합니다.
  
  지금 가입하고 음성 여정을 시작하세요!
Tags:
  - voicemeet
  - social
ReleaseNotesUrl: https://voicemeet.net/changelog
ManifestType: locale
ManifestVersion: 1.12.0
